# Generated by Django 5.1.4 on 2024-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genre'),
        ),
    ]
