# Generated by Django 5.1.4 on 2024-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_banner_url_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Banner Image URL'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
